<!-- TOC titleSize:1 tabSpaces:2 depthFrom:1 depthTo:6 withLinks:1 updateOnSave:1 orderedList:0 skip:0 title:1 charForUnorderedList:* -->
# Table of Contents
- [Table of Contents](#table-of-contents)
- [Error handling](#error-handling)
  - [Unrecoverable errors with `panic!`](#unrecoverable-errors-with-panic)
    - [Using a `panic!` backtrace](#using-a-panic-backtrace)
  - [Recoverable errors with `Result`](#recoverable-errors-with-result)
    - [Matching on different errors](#matching-on-different-errors)
    - [Shortcuts for panic on error: `unwrap` and `expect`](#shortcuts-for-panic-on-error-unwrap-and-expect)
    - [Propagating errors](#propagating-errors)
    - [A shortcut for propagating errors - The `?` operator](#a-shortcut-for-propagating-errors---the--operator)
    - [Where the `?` operator can be used](#where-the--operator-can-be-used)
  - [To `panic!` or not to `panic!`](#to-panic-or-not-to-panic)
    - [Examples, prototype code, and tests](#examples-prototype-code-and-tests)
    - [Cases we have more information than the compiler](#cases-we-have-more-information-than-the-compiler)
    - [Guidelines for error handling](#guidelines-for-error-handling)
    - [Creating custom types for validation](#creating-custom-types-for-validation)
<!-- /TOC -->

# Error handling
**Types of errors in Rust**. Recoverable and unrecoverable errors
* *Recoverable errors*. We report the problem to the user and retry the operation
* *Unrecoverable errors*. Always symptoms of bugs, hence we immediately stop the program

**Exceptions in Rust**. Rust does not have exceptions

$\to$ It has the type `Result<T, E>` for recoverable errors and the `panic!` macro to stop execution when the program encounters an unrecoverable error

## Unrecoverable errors with `panic!`
**`panic!` macro**. When the `panic!` macro executes, THE program will print a failure message, unwind and clean up the stack, and then quit
* *Usage*. A panic is commonly invoked when a bug of some kind has been detected and it is not clear how to handle the problem at the time of writing the program
* *Example*.

    ```rs
    fn main() {
        panic!("crash and burn");
    }
    ```

**Unwinding the stack or aborting in response to a panic**.
* *Unwinding*. By default, when a panic occurs, the program starts unwinding
    * *Unwinding*. Rust walks back up the stack and cleans up the data from each function it encounters
    * *Drawback*. This walking back and cleanup is a lot of work
        
        $\to$ Rust allows us to choose the alternative of immediately aborting
* *Aborting*. End the program without cleaning up
    
    $\to$ Memory used by the program will need to be cleaned up by the OS
    * *Usage*. If we want the resulting binary as small as possible
        
        $\to$ We can switch from unwinding to aborting upon a panic by adding `panic = 'abort'` to the appropriate `[profile]` sections in the `Cargo.toml` file, i.e.

        ```yaml
        [profile.release]
        panic = 'abort'
        ```

### Using a `panic!` backtrace
**Brief**. We can use the backtrace of the functions the `panic!` call came from to figure out the part of our code that is causing the problem

**Backtrace**. A list of all the functions, which have been called to get to a certain point
* *Reading backtraces*. Start from the top and read until we see files we wrote
    
    $\to$ That is the spot where the problem originated

## Recoverable errors with `Result`
**`Result` enum**. 
* *Definition*. Have two variants, `Ok` and `Err`, i.e.

    ```rs
    enum Result<T, E> {
        Ok(T),
        Err(E),
    }
    ```

    * *`T` and `E` parameters*. Generic type parameters
        * `T` represents the type of the value, which will be returned in a success case within the `Ok` variant
        * `E` represents the type of the error that will be returned in a failure case within the `Err` variant
* *Usage*. We can use the `Result` type and the functions defined on it in many different situations where the successful value and error value we want to return may differ
    * *Explain*. `Result` has these generic type parameters

**Similarity to `Option`**. Like the `Option` enum, the `Result` enum and its variants have been brought into scope by the prelude

$\to$ We do not need to specify `Result::` before the `Ok` and `Err` variants in the `match` arms
* *Example*.

    ```rs
    let f = File::open("hello.txt");
    let f = match f {
        Ok(file) => file,
        Err(error) => panic!("Problem opening the file: {:?}", error),
    };
    ```

### Matching on different errors
**Example**.

```rs
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let f = File::open("hello.txt");

    let f = match f {
        Ok(file) => file,
        Err(error) => match error.kind() {
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("Problem opening the file: {:?}", other_error)
            }
        },
    };
}
```

**Alternatives to using `match` with `Result<T, E>`**. The `match` expression is very useful but also very much a primitive

$\to$ We can use closures and `unwrap_or_else` method instead

* *Example*.

    ```rs
    use std::fs::File;
    use std::io::ErrorKind;

    fn main() {
        let f = File::open("hello.txt").unwrap_or_else(|error| {
            if error.kind() == ErrorKind::NotFound {
                File::create("hello.txt").unwrap_or_else(|error| {
                    panic!("Problem creating the file: {:?}", error);
                })
            } else {
                panic!("Problem opening the file: {:?}", error);
            }
        });
    }
    ```

### Shortcuts for panic on error: `unwrap` and `expect`
**Brief**. Using `match` works well enough, but it can be a bit verbose and does not always communicate intent well

$\to$ `Result<T, E>` type has many helper methods defined on it to do various, more specific tasks

**`unwrap` method**. A shortcut method implemented like the `match` expression
* *Idea*.
    * If the `Result` value is the `Ok` variant
        
        $\to$ `unwrap` will return the value inside the `Ok`
    * If the `Result` is the `Err` variant
        
        $\to$ `unwrap` will call the `panic!` macro
* *Example*.

    ```rs
    use std::fs::File;

    fn main() {
        let f = File::open("hello.txt").unwrap();
    }
    ```

**`expect` method**. Let us also choose the `panic!` error message
* *Purpose*. Using `expect` instead of `unwrap` and providing good error messages can convey your intent and make tracking down the source of a panic easier
* *Example*.

    ```rs
    use std::fs::File;

    fn main() {
        let f = File::open("hello.txt").expect("Failed to open hello.txt");
    }
    ```

### Propagating errors
**Propagating the error**. When a function’s implementation calls something that might fail

$\to$ We can return the error to the calling code for later handling
* *Explain*. We gives more control to the calling code, where there might be more information or logic dictating how the error should be handled
* *Example*.

    ```rs
    use std::fs::File;
    use std::io::{self, Read};

    fn read_username_from_file() -> Result<String, io::Error> {
        let f = File::open("hello.txt");

        let mut f = match f {
            Ok(file) => file,
            Err(e) => return Err(e),
        };

        let mut s = String::new();

        match f.read_to_string(&mut s) {
            Ok(_) => Ok(s),
            Err(e) => Err(e),
        }
    }
    ```

>**NOTE**. Error propagation is common in Rust that Rust provides the question mark operator `?` to make this easier

### A shortcut for propagating errors - The `?` operator
**The `?` operator**. A shortcut for propagating errors
* *Example*.

    ```rs
    use std::fs::File;
    use std::io;
    use std::io::Read;

    fn read_username_from_file() -> Result<String, io::Error> {
        let mut f = File::open("hello.txt")?;
        let mut s = String::new();
        f.read_to_string(&mut s)?;
        Ok(s)
    }
    ```

* *Idea*. The `?` placed after a `Result` value is defined to work as the `match` expressions defined to handle the `Result` values

    ```rs
    match f.read_to_string(&mut s) {
        Ok(_) => Ok(s),
        Err(e) => Err(e),
    }
    ```

    * If the value of the `Result` is an `Ok`
        
        $\to$ The value inside the `Ok` will be returned from the `?` expression, and the program will continue
    * If the value is an `Err`, the `Err` will be returned from the whole function
        
        $\to$ The error value gets propagated to the calling code
* *Difference from using `match`*.
    * Error values, which have the `?` operator called on them, go through the `from` function defined in the `From` trait in the standard library
        * *`from` function of `From` trait*. Used to convert errors from one type into another
        * *Explain*. When the `?` operator calls the `from` function
            
            $\to$ The error type received is converted into the error type defined in the return type of the current function
        * *Consequence*. This is useful when a function returns one error type to represent all the ways a function might fail, even if parts might fail for many different reasons
        * *Requirements*. There must be an `impl From<OtherError> for ReturnedError` to define the conversion in the trait’s `from` function
* *Benefits*. The `?` operator eliminates a lot of boilerplate and makes the function’s implementation simple

### Where the `?` operator can be used
**Usage of the `?` operator**. Used in functions, whose return type is compatible with the value the `?` is used on
* *Explain*. The `?` operator is defined to perform an early return of a value out of the function
* *Example*. The following code will not compile

    ```rs
    use std::fs::File;

    fn main() {
        let f = File::open("hello.txt")?;
    }
    ```

    * *Explain*. The `main` function has a return type incompatible with the type of the value we use `?` on
* *Solutions*.
    * *Option 1*. Change the return type of our function to be compatible with the value we are using the `?` operator on
    * *Option 2*. Use a match or one of the `Result<T, E>` methods to handle the `Result<T, E>` in some appropriate way

**Using `?` with `Option<T>`**. `?` can be used with `Option<T>` values

$\to$ As with using `?` on `Result`, we can only use `?` on `Option` in a function that returns an `Option`
* *Behavior of the `?` operator on an `Option<T>`*. Similar to the behavior when called on a `Result<T, E>`, i.e.
    * If the value is `None`, the `None` will be returned early from the function at that point
    * If the value is `Some`, the value inside the `Some` is the resulting value of the expression and the function continues
* *Example*.

    ```rs
    fn last_char_of_first_line(text: &str) -> Option<char> {
        text.lines().next()?.chars().last()
    }
    ```

**Mixing `?` with `Result` and `Option<T>`**. We can use the `?` operator on a `Result` in a function returning Result, and on an `Option` in a function returning `Option`

$\to$ However, we cannot mix and match
* *Explain*. The `?` operator will not automatically convert a `Result` to an `Option` or vice versa
* *Solution*. Use methods like the `ok` method on `Result` or the `ok_or` method on `Option` to do the conversion explicitly

**`main` function returning `Result`**. The `main` function is special since it is the entry and exit point of executable programs

$\to$ There are restrictions on what its return type can be for the programs to behave as expected
* *`main` function returning `Result`*. `main` can return a `Result<(), E>`
* *Example*.

    ```rs
    use std::error::Error;
    use std::fs::File;

    fn main() -> Result<(), Box<dyn Error>> {
        let f = File::open("hello.txt")?;

        Ok(())
    }
    ```

* *Idea*. When a `main` function returns a `Result<(), E>`, the executable will exit with a value of `0` if main returns `Ok(())`, otherwise with a nonzero value if main returns an `Err` value
    * *Analogy to C++*. Executables written in C return integers when they exit
        * Programs that exit successfully return the integer `0`
        * Programs that error return some integer other than `0`

## To `panic!` or not to `panic!`
**Brief**. How to decide when to call `panic!` and when to return `Result`
* *Idea*. When code panics, there is no way to recover

    >**NOTE**. We can call `panic!` for any error situation, whether there is a possible way to recover or not
    
    * By calling `panic!`, we are assuming that the situation is unrecoverable on behalf of the calling code
    * By returning a `Result` value, we give the calling code options, i.e.
        * The calling code may attempt to recover in an appropriate way for its situation, or
        * The calling code may decide that the `Err` is unrecoverable
            
            $\to$ It can call `panic!` and turn the recoverable error into an unrecoverable one
* *Conclusion*. Returning `Result` is a good default choice when defining a function that might fail

**When to use `panic!`**. When writing examples, prototype code, and tests

$\to$ It is more appropriate to write code that panics instead of returning a Result

### Examples, prototype code, and tests
**Brief**. 
* *Using `panic!` in examples*. When writing an example to illustrate some concept

    $\to$ Including robust error-handling code can make the example less clear
* *Using `panic!` in prototype code*. The `unwrap` and `expect` methods are very handy when prototyping, before we are ready to decide how to handle errors
    * *Explain*. They leave clear markers in the code for when we are ready to make our program more robust
* *Using `panic!` in tests*. If a method call fails in a test, the whole test should fail, even if that method is not the functionality under test
    * *Consequence*. Since `panic!` is how a test is marked as a failure
        
        $\to$ Calling `unwrap` or `expect` is exactly what should happen

### Cases we have more information than the compiler
**Brief**. It is appropriate to call `unwrap` when you have some other logic to ensure that the `Result` will have an `Ok` value
* *Problem*. Logic is not something the compiler understands, hence we still have a `Result` value that you need to handle
    * *Explain*. Whatever operation we are calling still has the possibility of failing in general, even though it is logically impossible in our particular situation
    * *Consequence*. If we can ensure, by manually inspecting the code, that we will never have an `Err` variant
        
        $\to$ It is perfectly acceptable to call `unwrap`

### Guidelines for error handling
**Using `panic!` in possibly bad code**. Use `panic!` when it is possible that the code could end up in a bad state
* *Bad state*. When some assumption, guarantee, contract, or invariant has been broken, plus one or more of the following
    * The bad state is something that is unexpected
    * The code after this point needs to rely on not being in this bad state
    * There is not a good way to encode this information in the types we use
* *Examples*.
    * *Using `panic!` when receiving inappropriate inputs*. If someone calls your code and passes in values that do not make sense

        $\to$ The best choice might be to call `panic!` and alert the person using the library to the bug in their code so they can fix it during development
    * *Using `panic!` when calling external code*. `panic!` is often appropriate when calling external code out of our control and it returns an invalid state that we have no way of fixing
    * *Using `panic!` when a failure is expected*. When failure is expected, it is more appropriate to return a `Result` than to make a `panic!` call
        * *Explain*. Returning a `Result` indicates that failure is an expected possibility that the calling code must decide how to handle
    * *Using `panic!` for inappropriate value*. When our code performs operations on values, our code should verify the values are valid first and panic if the values are not valid
        * *Explain*. This is mostly for safety reasons, i.e. attempting to operate on invalid data can expose our code to vulnerabilities
            * *Example*. The standard library will call `panic!` if we attempt an out-of-bounds memory access, i.e. trying to access memory that does not belong to the current data structure is a common security problem
        * *Function contract*. Functions often have contracts, i.e. their behavior is only guaranteed if the inputs meet particular requirements
            
            $\to$ Panicking when the contract is violated makes sense
            * *Explain*. 
                * A contract violation always indicates a caller-side bug and it is not a kind of error we want the calling code to have to explicitly handle
                * In fact, there is no reasonable way for calling code to recover

                    $\to$ The calling programmers need to fix the code
            
            >**NOTE**. Contracts for a function, especially when a violation will cause a panic, should be explained in the API documentation for the function

**Minimizing error checks in the code**. Having lots of error checks in all functions would be verbose and annoying
* *Solution*. Use Rust’s type system to do many of the checks
* *Example*. If our function has a particular type as a parameter, we can proceed with our code’s logic
    
    $\to$ We assume that the compiler has already ensured us have a valid value

### Creating custom types for validation
**Example**. Consider a code asking the user to guess a number between 1 and 100

```rs
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("Guess value must be between 1 and 100, got {}.", value);
        }

        Guess { value }
    }

    pub fn value(&self) -> i32 {
        self.value
    }
}
```